sudo: false
language: scala

# Only run aggregation 2.12
matrix:
  include:
    - scala: 2.10.7
      jdk: oraclejdk8
      script:
        - travis_wait sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION  test:compile test:doc
        - >
          travis_wait sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test
    - scala: 2.11.12
      jdk: oraclejdk8
      script:
        - travis_wait sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION scalafmt::test test:compile test:doc
        - >
          travis_wait sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test
    - scala: 2.12.4
      jdk: oraclejdk8
      script:
        - travis_wait sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION test:compile test:doc
        - >
          travis_wait sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' coverage test coverageReport
        - travis_wait sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION coverageAggregate
      after_success: sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION coveralls
cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete