sudo: false
language: scala

env:
  - SCALAJS_TEST_OPT=full

# Only run aggregation 2.12
matrix:
  include:
    - scala: 2.11.12
      jdk: openjdk8
      script:
        - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION scalafmtCheck scalafmtSbtCheck scala_2_11/test:compile scala_2_11/test:doc
        - travis_wait 30 sleep 1800 &
        - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION scala_2_11/test
    - scala: 2.12.11
      jdk: openjdk8
      script:
        - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION test:compile test:doc
        - travis_wait 30 sleep 1800 &
        - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION coverage test coverageReport
        - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION coverageAggregate
      after_success: sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION coveralls
    - scala: 2.12.10
      jdk: openjdk8
      script:
        - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION test:compile test:doc
        - travis_wait 30 sleep 1800 &
        - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION test
    - scala: 2.13.2
      jdk: openjdk8
      script:
        - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION test:compile test:doc
        - travis_wait 30 sleep 1800 &
        - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION test
    - scala: 2.13.1
      jdk: openjdk8
      script:
        - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION test:compile test:doc
        - travis_wait 30 sleep 1800 &
        - sbt -jvm-opts .travis-jvmopts ++$TRAVIS_SCALA_VERSION test
    - scala: 2.13.0
      jdk: openjdk8
      script:
        - sbt ++$TRAVIS_SCALA_VERSION scala_2_13/test:compile scala_2_13/test:doc
        - sbt ++$TRAVIS_SCALA_VERSION scala_2_13/test
cache:
  directories:
  - $HOME/.sbt/1.0
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
