sudo: false
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.10.6
  - 2.11.8
  - 2.12.0
script:
# Only run aggregation 2.11, for 2.12, only run the special dummy project
 - if [[ $TRAVIS_SCALA_VERSION == "2.12"* ]];
   then
     sbt ++$TRAVIS_SCALA_VERSION scala_2_12/test;
   elif [[ $$TRAVIS_SCALA_VERSION == "2.11"* ]];
   then
     sbt clean test:compile &&
     sbt coverage test coverageReport &&
     sbt coverageAggregate;
   else
     sbt clean test
   fi
after_success:
 - if [[ $TRAVIS_SCALA_VERSION == "2.11"* ]]; then
    sbt coveralls;
   fi
cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
