sudo: false
language: scala

# Only run aggregation 2.11, for 2.12, only run the special dummy project
matrix:
  include:
    - scala: 2.10.6
      jdk: oraclejdk8
      script: sbt ++$TRAVIS_SCALA_VERSION clean test:compile test
    - scala: 2.11.8
      jdk: oraclejdk8
      script:
        - sbt ++$TRAVIS_SCALA_VERSION coverage test:compile test coverageReport
        - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
      after_success: sbt ++$TRAVIS_SCALA_VERSION coveralls
    - scala: 2.12.1
      jdk: oraclejdk8
      script: sbt ++$TRAVIS_SCALA_VERSION scala_2_12/test:compile scala_2_12/test
cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
