## Base: https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html

name: Continuous integration
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11
            scala: 2.12.18
          - java: 11
            scala: 2.13.11
          - java: 11
            scala: 3.2.1
    runs-on: ubuntu-latest
    env:
      SCALAJS_TEST_OPT: full
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms6G -Xmx6G -Xss4M -XX:ReservedCodeCacheSize=256M -XX:MaxMetaspaceSize=1G -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms6G -Xmx6G -Xss4M -XX:ReservedCodeCacheSize=256M -XX:MaxMetaspaceSize=1G -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -Dfile.encoding=UTF-8
      SBT_OPTS:  -Denumeratum.useLocalVersion
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: olafurpg/setup-scala@v14
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Build and test
        shell: bash
        run: |
          case ${{ matrix.scala }} in
            2.12.18)
              sbt -v ++${{ matrix.scala }} scalafmtCheck scalafmtSbtCheck test:compile test:doc
              sbt -v ++${{ matrix.scala }} coverage test coverageReport
              sbt -v ++${{ matrix.scala }} coverageAggregate
              ;;
            *)
              sbt -v ++${{ matrix.scala }} test:compile test:doc
              sbt -v ++${{ matrix.scala }} test
              ;;
          esac
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1 -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1         -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                       -name "*.lock"               -delete || true
      - name: Upload coverage to Codecov
        if: ${{ matrix.scala == '2.12.18' }}
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
